# Generated by Django 4.2 on 2024-01-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_email_context_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='context_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
