# Generated by Django 4.2.7 on 2024-01-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_email_context_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set(),
        ),
    ]
