# Generated by Django 4.2.7 on 2024-01-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_emailtemplate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('name', 'version')},
        ),
    ]
