# Generated by Django 4.2 on 2023-12-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'verbose_name_plural': 'Emergency Contact'},
        ),
        migrations.AlterModelOptions(
            name='jobrole',
            options={'verbose_name_plural': 'Job role'},
        ),
        migrations.AlterModelOptions(
            name='performancereport',
            options={'verbose_name_plural': 'Performance Report'},
        ),
    ]
