# Generated by Django 4.2 on 2023-12-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name_plural': 'Job Application'},
        ),
        migrations.AlterModelOptions(
            name='jobapplicationdocument',
            options={'verbose_name_plural': 'Candidate Documents'},
        ),
        migrations.AlterModelOptions(
            name='jobapplicationremark',
            options={'verbose_name_plural': 'Candidate Application Remark'},
        ),
        migrations.AlterModelOptions(
            name='previousjobdetail',
            options={'verbose_name_plural': 'Candidate Previous Job Details'},
        ),
        migrations.AddField(
            model_name='jobapplicationremark',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
