# Generated by Django 4.2 on 2023-12-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Update', 'Update'), ('On hold', 'On hold'), ('Rejected', 'Rejected'), ('Blocked', 'Blocked'), ('Onboard', 'Onboard')], default='Pending Approval', max_length=20),
        ),
    ]
