# Generated by Django 4.2.7 on 2023-12-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_jobapplication_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='documentation_status',
            field=models.CharField(choices=[('Pending Review', 'Pending Review'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Update', 'Update'), ('On hold', 'On hold'), ('Rejected', 'Rejected'), ('Blocked', 'Blocked'), ('Approved', 'Approved')], default='Pending Review', max_length=20),
        ),
    ]
