# Generated by Django 5.0 on 2024-01-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('onboarding', '0005_candidatediscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='onboarding.jobapplication'),
            preserve_default=False,
        ),
    ]
